### ISSUE TITLE
Pravo na zdravstveno osiguranje?

### ISSUE THREAD

**Issue by abdurahmanadilovic** [komljen/fbih-freelancers#1]
Meni su rekli u opcini i na par mjesta da 4% koje moram platiti za zdravstveno osiguranje ne garantuje zdravstveno osiguranje, nego da moram pored toga platiti sebi zdravstvo?

**Comment by komljen** [comment]
To nije tacno. Zato sto ne postoji nikakva razlika izmedju uplate tih 4% i uplate za dobrovoljno zdravstveno. Isti racun, vrsta prihoda i ostalo. Prijavis se na dobrovoljno zdravstveno, i onda uplacujes tih 4%. Moguce je da nema po defaultu dok ne prijavis.

Cak su mi u ZZO rekli da nema smisla da ponovo placam ako sam vec platio odredjen iznos na racun, jer je to isto, te da samo doplatim razliku ako je manje.

**Comment by abdurahmanadilovic** [comment]
Moguce da su mislili na situaciju kad je neko vec zaposlen, mora platiti zdravstvo koje vec placa i od njega nema nista. Hvala na odgovoru
