### ISSUE TITLE
Osnivanje doo, obrt, ostalo...

### ISSUE THREAD

**Issue by sanel** [komljen/fbih-freelancers#2]
Mozda ne bi bilo lose da imamo detalje sta je potrebno za doo, obrt ili kako nastaviti kao fizicko lice. Ljude najcesce zanima koje su razlike doo vs. obrt, cijene, mjesecni troskovi itd.

**Comment by komljen** [comment]
Slazem se, imam ja dosta informacija, ali nemam bas vremena. Pa kad stignem.
