### ISSUE TITLE
Dobrovoljno zdravstveno, dodatni trošak ili uključeno u AMS?

### ISSUE THREAD

**Issue by edgolub** [komljen/fbih-freelancers#4]
"Dobrovoljno zdravstveno Vas kosta ~70KM mjesecno."
Jeli se to pika kao plus na ovih 4% što se plaća ili tih 4% pokrije te troškove dobrovoljnog?

Vidim da u ovom članku https://www.mreza-mira.net/vijesti/poslovi/freelancing-u-fbih/ ( piše da si autor @komljen ), da ako plaćate putem AMS obrasca ne morate dodatno plaćati za dobrovoljno. Jeli to potrđeno? Imaš li ličnog iskustva. 

Meni iz zdravstvenog zavoda kažu "nemam pojma", i da moram čekati odgovor sa kantonalnog nivoa, jer ne znaju. Pa da vidim kakav su odgovor drugi dobili.

**Comment by komljen** [comment]
> Vidim da u ovom članku https://www.mreza-mira.net/vijesti/poslovi/freelancing-u-fbih/ ( piše da si autor @komljen ), da ako plaćate putem AMS obrasca ne morate dodatno plaćati za dobrovoljno. Jeli to potrđeno? Imaš li ličnog iskustva.

U trenutku kad je clanak napisan, rekli su mi da se ubrajaju ti troskovi. Medjutim kasnije opet kad sam isao do direktora ZZO, onda su potrdili da se to ne ubraja i da cekaju taj neki odgovor. Od toga je proslo vise od godinu dana.

Za sad, dodatno platis tih 70KM da bi imao zdravstveno.

**Comment by edgolub** [comment]
@komljen hvala na odgovoru!

Vidio sam na drugim mjestima da je ista info data kao u ovom tvom članku, pretpostavljam da su ljudi citirali tebe, jer je i meni rečeno da dobrovojlno zdratstveno se plaća zasebno od ovog obaveznog na primanja.
